(wip basic improvements
bulk formatting with default Intellj Python style
removed unnecessary backslashes (as per Intellij)

moved tests to hide them

(wip) address use of globals - moved dictionaries to `dicts`

regression testing

```
$TERMOLATOR/run_termolator.sh $NYU_DIR/foreground.list $NYU_DIR/background.list .txt DAVETEST "True" "False" 8400 1400 $TERMOLATOR  "" "" "False"
sort master/DAVETEST.all_terms > master/DAVETEST.all_terms.sorted
sort improvements/DAVETEST.all_terms > improvements/DAVETEST.all_terms.sorted

sort master/DAVETEST.scored_output > master/DAVETEST.scored_output.sorted
sort improvements/DAVETEST.scored_output > improvements/DAVETEST.scored_output.sorted

# not diff
diff /development/projects/04_clients/czi/ds/The_Termolator/tmpexec/master/DAVETEST.all_terms.sorted /development/projects/04_clients/czi/ds/The_Termolator/tmpexec/improvements/DAVETEST.all_terms.sorted

# some diff at the 4th decimal
bcompare /development/projects/04_clients/czi/ds/The_Termolator/tmpexec/master/DAVETEST.scored_output.sorted /development/projects/04_clients/czi/ds/The_Termolator/tmpexec/improvements/DAVETEST.scored_output.sorted
```

applied `typing` to regular expressions as per https://docs.python.org/3/library/typing.html#typing.re

more typing improvements
from the modified files mypy only complains about abbreviate.py

 ```
 $ mypy find_terms.py
 abbreviate.py:119: error: List item 2 has incompatible type "str"
 abbreviate.py:119: error: List item 3 has incompatible type "str"
 abbreviate.py:135: error: List item 2 has incompatible type "str"
 abbreviate.py:135: error: List item 3 has incompatible type "str"
 abbreviate.py:692: error: Incompatible types in assignment (expression has type "str", variable has type "bool")
 abbreviate.py:694: error: Incompatible types in assignment (expression has type "str", variable has type "bool")
 abbreviate.py:697: error: Incompatible types in assignment (expression has type "str", variable has type "bool")
 abbreviate.py:699: error: Incompatible types in assignment (expression has type "str", variable has type "bool")
 abbreviate.py:751: error: Incompatible types in assignment (expression has type "str", variable has type "bool")
 abbreviate.py:769: error: No overload variant of "search" matches argument types [builtins.str, builtins.bool]
 abbreviate.py:770: error: Incompatible types in assignment (expression has type "bool", variable has type "str")
 abbreviate.py:782: error: Incompatible types in assignment (expression has type List[str], variable has type "bool")
 abbreviate.py:784: error: Argument 1 to "len" has incompatible type "bool"; expected "Sized"
 abbreviate.py:786: error: "bool" has no attribute "extend"
 abbreviate.py:787: error: Incompatible types in assignment (expression has type List[int], variable has type "bool")
 abbreviate.py:789: error: Incompatible types in assignment (expression has type List[int], variable has type "bool")
 abbreviate.py:789: error: Argument 1 to "lookup_abbreviation" has incompatible type "bool"; expected "str"
 abbreviate.py:791: error: Incompatible types in assignment (expression has type "bool", variable has type "str")
 abbreviate.py:798: error: Incompatible types in assignment (expression has type "bool", variable has type "str")
 abbreviate.py:800: error: Incompatible types in assignment (expression has type List[int], variable has type "bool")
 abbreviate.py:805: error: Incompatible types in assignment (expression has type List[int], variable has type "bool")
 abbreviate.py:809: error: Incompatible types in assignment (expression has type "bool", variable has type "str")
 abbreviate.py:811: error: Value of type "bool" is not indexable
 abbreviate.py:814: error: Value of type "bool" is not indexable
 abbreviate.py:815: error: Incompatible types in assignment (expression has type "int", variable has type "bool")
 abbreviate.py:816: error: Incompatible types in assignment (expression has type "str", variable has type "bool")
 abbreviate.py:817: error: Incompatible types in assignment (expression has type "int", variable has type "bool")
 abbreviate.py:819: error: Incompatible types in assignment (expression has type "int", variable has type "bool")
 abbreviate.py:820: error: Incompatible types in assignment (expression has type "str", variable has type "bool")
 abbreviate.py:821: error: Incompatible types in assignment (expression has type "int", variable has type "bool")
 abbreviate.py:822: error: Value of type "bool" is not indexable
 abbreviate.py:823: error: Value of type "bool" is not indexable
 abbreviate.py:824: error: Value of type "bool" is not indexable
 abbreviate.py:825: error: Value of type "bool" is not indexable
 abbreviate.py:832: error: Incompatible types in assignment (expression has type List[str], variable has type "bool")
 abbreviate.py:833: error: Argument 1 to "len" has incompatible type "bool"; expected "Sized"
 abbreviate.py:835: error: "bool" has no attribute "extend"
 abbreviate.py:836: error: Incompatible types in assignment (expression has type List[int], variable has type "bool")
 abbreviate.py:841: error: Incompatible types in assignment (expression has type List[int], variable has type "bool")
 abbreviate.py:846: error: Value of type "bool" is not indexable
 abbreviate.py:847: error: Incompatible types in assignment (expression has type "int", variable has type "bool")
 abbreviate.py:848: error: Incompatible types in assignment (expression has type "str", variable has type "bool")
 abbreviate.py:850: error: Incompatible types in assignment (expression has type "int", variable has type "bool")
 abbreviate.py:851: error: Incompatible types in assignment (expression has type "int", variable has type "bool")
 abbreviate.py:852: error: Incompatible types in assignment (expression has type "int", variable has type "bool")
 abbreviate.py:853: error: Value of type "bool" is not indexable
 abbreviate.py:854: error: Value of type "bool" is not indexable
 abbreviate.py:855: error: Value of type "bool" is not indexable
 abbreviate.py:856: error: Value of type "bool" is not indexable
 abbreviate.py:864: error: Incompatible types in assignment (expression has type "bool", variable has type Match[str])
 abbreviate.py:868: error: Incompatible types in assignment (expression has type List[int], variable has type "bool")
 abbreviate.py:876: error: Value of type "bool" is not indexable
 abbreviate.py:877: error: Incompatible types in assignment (expression has type "str", variable has type "bool")
 abbreviate.py:878: error: Incompatible types in assignment (expression has type "int", variable has type "bool")
 abbreviate.py:880: error: Incompatible types in assignment (expression has type "int", variable has type "bool")
 abbreviate.py:881: error: Incompatible types in assignment (expression has type "int", variable has type "bool")
 abbreviate.py:881: error: Argument 1 to "len" has incompatible type "bool"; expected "Sized"
 abbreviate.py:882: error: Value of type "bool" is not indexable
 abbreviate.py:891: error: Incompatible types in assignment (expression has type Dict[str, str], variable has type "bool")
 abbreviate.py:891: error: Argument 1 to "make_nyu_entity" has incompatible type "bool"; expected "str"
 abbreviate.py:891: error: Argument 2 to "make_nyu_entity" has incompatible type "bool"; expected "str"
 abbreviate.py:891: error: Argument 3 to "make_nyu_entity" has incompatible type "bool"; expected "str"
 abbreviate.py:891: error: Argument 4 to "make_nyu_entity" has incompatible type "bool"; expected "str"
 abbreviate.py:892: error: Incompatible types in assignment (expression has type Dict[str, str], variable has type "bool")
 abbreviate.py:892: error: Argument 1 to "make_nyu_entity" has incompatible type "bool"; expected "str"
 abbreviate.py:892: error: Argument 3 to "make_nyu_entity" has incompatible type "bool"; expected "str"
 abbreviate.py:897: error: Value of type "bool" is not indexable
 abbreviate.py:898: error: Value of type "bool" is not indexable
 abbreviate.py:903: error: Incompatible types in assignment (expression has type "int", variable has type "bool")
```